language: cpp
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
sudo: required
dist: trusty
services: docker
install: true
before_install:
    - ./install_requirements.sh $TRAVIS_OS_NAME
script:
    - ./build.sh ${TRAVIS_OS_NAME} ${TRAVIS_TAG}

deploy:
  provider: releases
  api_key:
    secure: V79Mbikj+TadfYr3kqOsMR3xY9HmfWVXupD4BH5a5Htl6I6APl9hQjXfQ2u54Er73H8kXDUcc1N6Z4eoi7lNDqp33hKnR8ya3c+xHhlblhULySUBR3StUil/LV0KCqz54spk+3Djb857fe5lTpNea9PCHTsG3r/BJs6I56ZqX3zFFmcYrth7hqLoNXJPcXOLWP2+RJCTnikRYTqG3/PH4Lkm+fZgo/RxVq7eA4eE64ceFicB0F/TO+4bauolDN5YgnffHLm0SztBkXWvtnq3B/5/2aIqoAEHWjHntG9biTa25Ir0MbSlb+fkm6GVkplETgQB6HCoUSIqB8hFHn+hl/ADBjGFaRz+3SDwrdnPlPBeCwV42r1GyNxRKX3t8yMmbszuSZeiVL7PMDfUHHozTLlwN+1EqyoJBtIBXK0mnh3lfid7QRub1/PqLZcOhOiFeTroH6xapEDuivTEp6Va1MJHO2/45FzNOKF8hFTSdQtkjuM6NFByhOEBHix8SGnXKTZcMLPDkGLCBIpRUa8uknsM/KNlpTyMDZL9hFrmvvo9vt0AneBWk3q0ibl5qCXdqcbhwJfDaiFBekpy/C7VcIhwtaCWI4OqjawREDeONBtmsLq3FI/+MsB4u+UlPy/2Pnv65yVYsnR8IyfKTmujcF2XwHokGMYR7pjkRZqN8QE=
  file_glob: true
  file:
      - "build/tracelib-*Tools*"
      - "build/tracelib-*Documentation*"
      - "build/tracelib-*Library*"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_COMPILER = clang
    repo: froglogic/tracetool

