version: '{build}'
environment:
    matrix:
        - TRACETOOL_ARCH: x86
        - TRACETOOL_ARCH: x64
matrix:
    fast_finish: true

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files\doxygen\ -> appveyor.yml

install:
    - cinst ninja doxygen.install

build_script:
    - call build.cmd %TRACETOOL_ARCH% %APPVEYOR_REPO_TAG%

test_script:
    - call test.cmd

artifacts:
    path: 'build\tracelib-*.zip'

deploy:
    provider: GitHub
    artifact: /tracelib-.*zip/
    auth_token:
        secure: GrqKmmmfswKC5v/gUBcZfcNIQ0ay8rwl70ppM/xwi0E5a4gVxcZcMObKmxohIBI9
    on:
        APPVEYOR_REPO_TAG: true
