branches:
    only:
        - master

install:
    - cinst ninja doxygen.install
    - call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
    # Check compiler version
    - cl
    - set CMAKE_PREFIX_PATH=C:\Qt\5.6\msvc2013

build_script:
    - mkdir build 
    - cd build
    - cmake -G "Ninja" ..
    - ninja

test_script:
    - ninja test
